update_sensors:
  name: Update Sensors
  description: Manually update sensor values from the UltraLite PRO meter.
  fields:
    device_id:
      name: Device ID
      description: Device ID to update (optional, updates all devices if not specified)
      example: "a1b2c3d4e5f6g7h8"
      selector:
        device:
          integration: ultralite_pro
